theme: jekyll-theme-modernist
title: Welcome to Morgan Ward's Machine Learning Showcase!
description: This page is intended to show some of the past projects regarding machine learning that I have completed.
